# Generated by Django 5.2.4 on 2025-07-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footimage',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footimage',
            name='length_inches',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footimage',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('complete', 'Complete'), ('error', 'Error')], default='processing', max_length=10),
        ),
        migrations.AddField(
            model_name='footimage',
            name='width_inches',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
