# Generated by Django 5.2.4 on 2025-07-13 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='footimage',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footimage',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='footimage',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='footimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FootMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foot_length_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('foot_width_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('arch_height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('measurement_confidence', models.DecimalField(decimal_places=2, default=0.8, max_digits=3)),
                ('measurement_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('style_code', models.CharField(blank=True, max_length=50)),
                ('price_range', models.CharField(blank=True, max_length=20)),
                ('availability_status', models.CharField(default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shoecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_size_us', models.DecimalField(decimal_places=1, max_digits=3)),
                ('similarity_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('recommendation_date', models.DateTimeField(auto_now_add=True)),
                ('user_feedback', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('foot_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.footmeasurement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shoe')),
            ],
        ),
        migrations.CreateModel(
            name='ShoeMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_us', models.DecimalField(decimal_places=1, max_digits=3)),
                ('size_eu', models.IntegerField(blank=True, null=True)),
                ('length_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('arch_height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('measurement_date', models.DateField(auto_now_add=True)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='core.shoe')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
