# Generated by Django 5.2.4 on 2025-07-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_footimage_error_message_footimage_length_inches_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('U', 'Unisex')], max_length=1)),
                ('us_size', models.DecimalField(decimal_places=1, max_digits=4)),
                ('width_category', models.CharField(choices=[('N', 'Narrow'), ('D', 'Regular'), ('W', 'Wide')], max_length=1)),
                ('function', models.CharField(max_length=100)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
