# Generated by Django 5.2.4 on 2025-07-17 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shoe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='footimage',
            name='area_sq_inches',
            field=models.FloatField(blank=True, help_text='Area in square inches', null=True),
        ),
        migrations.AddField(
            model_name='footimage',
            name='perimeter_inches',
            field=models.FloatField(blank=True, help_text='Perimeter in inches', null=True),
        ),
        migrations.AddField(
            model_name='footimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foot_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoe',
            name='insole_area',
            field=models.FloatField(blank=True, help_text='Area in square inches', null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='insole_image',
            field=models.ImageField(blank=True, help_text='Upload insole photo to automatically calculate measurements', null=True, upload_to='insole_images/'),
        ),
        migrations.AddField(
            model_name='shoe',
            name='insole_length',
            field=models.FloatField(blank=True, help_text='Length in inches', null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='insole_perimeter',
            field=models.FloatField(blank=True, help_text='Perimeter in inches', null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='insole_width',
            field=models.FloatField(blank=True, help_text='Width in inches', null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='function',
            field=models.CharField(choices=[('casual', 'Casual'), ('hiking', 'Hiking'), ('work', 'Work'), ('running', 'Running')], max_length=20),
        ),
    ]
