# Generated by Django 5.2.4 on 2025-07-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_footimage_user'),
        ('core', '0005_add_shoe_image'),
    ]

    operations = [
    ]
