# Generated by Django 5.2.4 on 2025-07-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_0004_footimage_user_0005_add_shoe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='shoe_image',
        ),
        migrations.AddField(
            model_name='shoe',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct URL to the product image', null=True),
        ),
    ]
