# Generated by Django 5.2.4 on 2025-08-12 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_0004_footimage_user_0005_add_shoe_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='shoe_image',
        ),
        migrations.AddField(
            model_name='footimage',
            name='area_sqin',
            field=models.FloatField(blank=True, help_text='Foot area in square inches', null=True),
        ),
        migrations.AddField(
            model_name='footimage',
            name='perimeter_inches',
            field=models.FloatField(blank=True, help_text='Foot perimeter in inches', null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='shoe_image_url',
            field=models.URLField(blank=True, help_text="URL to the shoe product image (e.g., from manufacturer's website or CDN)", null=True),
        ),
        migrations.AlterField(
            model_name='footimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foot_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
