# Generated by Django 5.2.4 on 2025-08-13 03:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_shoe_shoe_image_footimage_area_sqin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_guest_session',
                'indexes': [models.Index(fields=['created_at'], name='core_guest__created_89b36d_idx'), models.Index(fields=['last_accessed'], name='core_guest__last_ac_6ff95b_idx')],
            },
        ),
        migrations.AddField(
            model_name='footimage',
            name='guest_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foot_images', to='core.guestsession'),
        ),
    ]
