# Generated by Django 5.2.4 on 2025-08-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_guest_session_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, help_text='Domain name (e.g., nordstromrack.com)', max_length=100)),
                ('selector', models.TextField(help_text='CSS selector for price element')),
                ('success_count', models.PositiveIntegerField(default=0, help_text='Number of successful extractions')),
                ('total_attempts', models.PositiveIntegerField(default=0, help_text='Total extraction attempts')),
                ('last_success', models.DateTimeField(blank=True, help_text='Last successful extraction', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to use this selector')),
            ],
            options={
                'indexes': [models.Index(fields=['domain', 'is_active'], name='core_prices_domain_249d1d_idx'), models.Index(fields=['success_count', 'total_attempts'], name='core_prices_success_5cb069_idx')],
                'unique_together': {('domain', 'selector')},
            },
        ),
    ]
